-- NOTE: This file is auto generated by ./sql-generator

-- PersonUserRepository.getForOwner
select
  "person_user"."personGroupId" as "personId",
  "person_user"."sharedById",
  "person_user"."sharedWithId",
  "person_user"."role",
  (
    select
      to_json(obj)
    from
      (
        select
          *
        from
          "user"
        limit
          $1
      ) as obj
  ) as "sharedWith"
from
  "person_user"
  inner join "user" on "user"."id" = "person_user"."sharedWithId"
where
  "person_user"."sharedById" = $2
